# Generated by Django 4.2.30 on 2026-05-14 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('file_path', models.CharField(blank=True, help_text='Path to pre-existing file on disk', max_length=1024, null=True)),
                ('file_type', models.CharField(choices=[('he5', 'PRISMA HE5'), ('tiff', 'GeoTIFF'), ('envi', 'ENVI HDR/IMG')], default='he5', max_length=10)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('processing', 'Processing'), ('error', 'Error')], default='ready', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rows', models.IntegerField(blank=True, null=True)),
                ('cols', models.IntegerField(blank=True, null=True)),
                ('bands', models.IntegerField(blank=True, null=True)),
                ('vnir_bands', models.IntegerField(blank=True, null=True)),
                ('swir_bands', models.IntegerField(blank=True, null=True)),
                ('wavelengths_vnir', models.JSONField(blank=True, null=True)),
                ('wavelengths_swir', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SpectralProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Profile', max_length=100)),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('spectrum', models.JSONField()),
                ('wavelengths', models.JSONField()),
                ('sensor_type', models.CharField(default='VNIR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.datafile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('radiometric', 'Radiometric Correction'), ('geometric', 'Geometric Correction'), ('atmospheric', 'Atmospheric Correction'), ('index', 'Spectral Index'), ('pca', 'PCA Analysis'), ('classification', 'Classification')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='processed/')),
                ('log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.datafile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
