# Generated by Django 4.2.30 on 2026-05-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingjob',
            name='job_type',
            field=models.CharField(choices=[('radiometric', 'Radiometric Correction'), ('geometric', 'Geometric Correction'), ('atmospheric', 'Atmospheric Correction'), ('index', 'Spectral Index'), ('pca', 'PCA Analysis'), ('ppi', 'PPI Endmember Extraction'), ('sam', 'SAM Target Detection'), ('lsu', 'Linear Spectral Unmixing'), ('classification', 'Classification'), ('clustering', 'Clustering')], max_length=30),
        ),
    ]
